# .github/workflows/ci.yml
 
# Continuous Integration (CI) Workflow
name: ci
 
# This workflow will run whenever we push commits to the `main` branch, or
# whenever there's a pull request to the `main` branch, but ONLY when
# files in the fragments/ directory are changed
on:
  pull_request:
    branches:
      - main
    paths:
      - 'fragments/**'
  push:
    branches:
      - main
    paths:
      - 'fragments/**'
 
jobs:
  lint:
    # Give your job a name that will show up in the GitHub Actions web UI
    name: ESLint
    # We'll run this on a Linux (Ubuntu) VM, since we'll deploy on Linux too.
    runs-on: ubuntu-latest
    # We run these steps one after the other, and if any fail, we stop the process
    steps:
      # Check out code
      - name: Check out code
        uses: actions/checkout@v4
 
      # Setup node
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          # Use node LTS
          node-version: 'lts/*'
          # Cache npm dependencies so they don't have to be downloaded next time
          cache: 'npm'
          # Specify the cache dependency path for the fragments directory
          cache-dependency-path: fragments/package-lock.json
 
      # Change to fragments directory and install dependencies
      - name: Install node dependencies
        working-directory: ./fragments
        # Use `ci` vs. `install`
        run: npm ci
 
      # Run ESLint from fragments directory
      - name: Run ESLint
        working-directory: ./fragments
        run: npm run lint

    # Lint our Dockerfile using Hadolint
  dockerfile-lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/hadolint-action
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: fragments/Dockerfile

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
 
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: package-lock.json
 
      - name: Install root dependencies
        run: npm ci

      - name: Install node dependencies and run Tests
        working-directory: ./fragments
        run: npm install-ci-test

  docker-hub:
    name: Build and Push to Docker Hub
  # Don't bother running this job unless the other three all pass
    needs: [lint, dockerfile-lint, unit-tests, integration-tests]
    runs-on: ubuntu-latest
    steps:
  # Set up buildx for optimal Docker Builds, see:
  # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out code
        uses: actions/checkout@v4    
      # Build and Push an Image to Docker Hub
      - name: Build and push
        env:
          # Define an Environment Variable with our Docker Hub Repo
          # Replace `username` with your Docker Hub username and `fragments
          # with whatever you've named your Docker Hub repo
          DOCKERHUB_REPO: hansonchieu/fragments
          # Define an Environment Variable with the current git commit's
          # sha: sha-87f664e01bb5f242faa411e9e7fb9e75a58ae767
          # Use the `github` context to get this, see:
          # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          SHA_TAG: sha-${{ github.sha }}
        uses: docker/build-push-action@v6
        with:
          context: ./fragments
          file: ./fragments/Dockerfile
          push: true
          # Use 3 tags :sha-sha-7d821bd14e0d6c381dc57a5369ae1a3a9220664f, :main, and :latest
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.SHA_TAG }}, ${{ env.DOCKERHUB_REPO }}:main, ${{ env.DOCKERHUB_REPO }}:latest
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install node dependencies
        # NOTE: we need to install dev dependencies too vs. production only for hurl
        working-directory: ./fragments
        run: npm install
      - name: Build Containers
        working-directory: ./fragments
        run: docker compose up -d
      - name: Setup Local AWS Resources
        working-directory: ./fragments 
      # NOTE: this file needs to be made executable *before* you check into git:
        # $ chmod +x ./scripts/local-aws-setup.sh
        run: ./scripts/local-aws-setup.sh
      - name: Run Hurl Tests
        run: npm run test:integration


  